// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using OpenQA.Selenium.IE;
using Unit_Desktop.Page_Object;
using OpenQA.Selenium.Support.PageObjects;
using Unit_Desktop;
using System.Diagnostics.Eventing.Reader;
using System.Security.Cryptography.X509Certificates;

namespace ST01CustomerEdit

{

    public class CT02ValidarCamposObrigatorios
    {
        private IWebDriver driver;
        private WebDriverWait wait;

        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;

        [SetUp]
        public void SetUp()
        {
            driver = Comandos.GetBrowserLocal(driver, "chrome");
            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
            wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }

        [TearDown]
        protected void TearDown()
        {
            Thread.Sleep(3000);

            driver.SwitchTo().Window(driver.WindowHandles[0]);

            driver.FindElement(By.CssSelector("#cmdLogoff")).Click();

            driver.Quit();
        }

        [Test]
        public void CT01ValidarCamposObrigatoriosTela()
        {

            // Módulo Clientes
            driver.FindElement(By.CssSelector("#navbar > ul > li:nth-child(4) > a")).Click();

            // switch para o frame Clientes
            driver.SwitchTo().Frame(1);

            // aguarda o item ser visivel para continuação da thread
            wait.Until(ExpectedConditions.VisibilityOfAllElementsLocatedBy(By.XPath("//*[@id='tbr_t0']/tbody/tr/td[2]")));

            // botão Nova pessoa
            driver.FindElement(By.XPath("//*[@id='tbr_t0']/tbody/tr/td[2]")).Click();

            // switch para o pop-up
            driver.SwitchTo().Window(driver.WindowHandles[1]);

            // botão Salvar
            driver.FindElement(By.CssSelector("#tbr_i0")).Click();

            // Validação dos campos obrigatórios
            StringAssert.Contains("Por favor verifique os seguintes itens:", driver.FindElement(By.Id("slideMain_valSummary")).Text);

        }
    }
}

