// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using OpenQA.Selenium.IE;
using Unit_Desktop.Page_Object;
using OpenQA.Selenium.Support.PageObjects;
using Unit_Desktop;
using System.Diagnostics.Eventing.Reader;
using System.Security.Cryptography.X509Certificates;

namespace ST01Desktop

{

    public class ST01Cases
    {
        private IWebDriver driver;
        private WebDriverWait wait;

        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;

        [SetUp]
        public void SetUp()
        {
            driver = Comandos.GetBrowserLocal(driver, "chrome");
            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
            wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }

        [TearDown]
        protected void TearDown()
        {
            Thread.Sleep(3000);

            driver.SwitchTo().Window(driver.WindowHandles[0]);

            driver.FindElement(By.CssSelector("#cmdLogoff")).Click();

            driver.Quit();
        }

        [Test]
        public void CAS01ValidarLayoutTela()
        {




            driver.FindElement(By.CssSelector("#navbar > ul > li:nth-child(6) > a")).Click();

            //driver.SwitchTo().Frame(1);

            Thread.Sleep(5000);

            driver.FindElement(By.XPath("//*[@id='slideResult_txtSearchValue']")).SendKeys("QA - 20200521000018");

            //wait.Until(ExpectedConditions.VisibilityOfAllElementsLocatedBy(By.XPath("//*[@id='tbr_t0']/tbody/tr/td[2]")));

            driver.FindElement(By.CssSelector("#slideResult_grdResults > tbody > tr.resultsDGitem > td:nth-child(1) > a")).Click();

            //driver.SwitchTo().Window(driver.WindowHandles[1]);


            //Page object



            //driver.FindElement(By.CssSelector("#nav-menu-item-5643 .item_text")).Click();

            //Thread.Sleep(5000);




        }

    }
}